//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.06 at 01:34:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/authentication/uid-bfd-response/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.gov.uidai.authentication.uid_bfd_response._1;
